
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600s"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "900"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "900"
  
spec:
  rules:
  - host: k8stest.sdspns-tst.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /AdaptikAuthority
        pathType: Prefix
        backend:
          service:
            name: sdk8s-ath-am
            port:
              number: 8080
      - path: /AdaptikPolicy
        pathType: Prefix
        backend:
          service:
            name: sdk8s-pol-am
            port:
              number: 8080
      - path: /AdaptikBilling
        pathType: Prefix
        backend:
          service:
            name: sdk8s-bil-am
            port:
              number: 8080
      - path: /AdaptikWork
        pathType: Prefix
        backend:
          service:
            name: sdk8s-pol-wm
            port: 
              number: 8080
      - path: /AdaptikProducer
        pathType: Prefix
        backend:
          service:
            name: sdk8s-prd-am
            port: 
              number: 8080

---



apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
            <head>
                    <title>Sapiens: CoreSuite for Property & Casualty</title>
                    <link rel="stylesheet" href="fonts/stylesheet.css" type="text/css" charset="utf-8" />
                    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" charset="utf-8" />

                    <style>
                            * {
                                    box-sizing: border-box;
                            }

                            html {
                                    font-size: 10px;
                            }

                            body {
                                    font-size: 1em;
                                    background: rgb(242,242,242);
                                    background: radial-gradient(circle, rgba(242,242,242,1) 0%, rgba(245,242,242,1) 56%, rgba(183,183,183,1) 100%);
                                    font-family: 'rubiklight';
                            }

                            #left {
                                    position: fixed;
                                    left: 0;
                                    top: 0;
                                    bottom: 0;
                                    width: 35rem;
                                    padding-top: 20rem;

                                    background: #004680;
                            }

                            #right {
                                    margin-left: 37rem;
                                    margin-top: 12rem;
                            }

                            #right div {
                                    font-size: 2rem;
                                    margin: 1.5rem;
                            }

                            #right a {
                                    color: #004680;
                                    text-decoration: none;
                                    margin-right: 1rem;
                            }

                            #right label {
                                    display: inline-block;
                                    width: 18rem;
                            }

                            #sapiensLogo {
                                display: block;

                                background-image: url(images/sapiens.png);
                                background-repeat: no-repeat;
                                background-size: contain;

                                height: 15rem;
                                margin: 0 5rem;
                            }

                            .spacer {
                                    visibility: hidden;
                                    margin-right: 1rem;
                            }

                            h1 {
                                    color: #00a7a7;
                                    font-size: 3rem;
                                    margin: 0 0 5rem 1.4rem;
                            }
                    </style>
            </head>
            <body>
                    <div id="left">
                            <span id="sapiensLogo"></span>
                            <span id="projectLogo"></span>
                    </div>

                    <div id="right">
                            <h1>CoreSuite for Property &amp; Casualty</h1>
                            <div>
                                    <label>PolicyPro</label>
                                    <a href="/AdaptikPolicy/AMEntryPoint?theme=adaptik-light&pageCode=HOME" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <a href="/AdaptikPolicy/AMEntryPoint?theme=adaptik-light&pageCode=SEARCH" target="_blank"><i class="fa fa-search fa-lg"></i></a>
                                    <a href="/PDPolicy" target="_blank"><i class="fa fa-gear fa-lg"></i></a>
                            </div>
                            <div>
                                    <label>BillingPro</label>
                                    <a href="/AdaptikBilling/BillingEntryPoint?pageCode=BILLING_LAUNCH&theme=adaptik-light" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                                    <a href="/PDBilling" target="_blank"><i class="fa fa-gear fa-lg"></i></a>
                            </div>
                            <div>
                                    <label>Work ManagerPro</label>
                                    <a href="/AdaptikWork/TMEntryPoint?pageCode=MYTASKS&appMode=N" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                            </div>
                            <div>
                                    <label>AuthorityPro</label>
                                    <a href="/AdaptikAuthority/AMEntryPoint?theme=adaptik-light&pageCode=LAUNCH" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                                    <a href="/PDAuthority" target="_blank"><i class="fa fa-gear fa-lg"></i></a>
                            </div>
                             <div>
                                    <label>ProducerPro</label>
                                    <a href="/AdaptikProducer/AMEntryPoint?theme=adaptik-light&pageCode=SEARCH" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                                    <a href="/PDProducer" target="_blank"><i class="fa fa-gear fa-lg"></i></a>
                            </div>
                            <div>
                                    <label>ClaimsPro</label>
                                    <a href="/iip" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                                    <a href="/sysadmin" target="_blank"><i class="fa fa-gear fa-lg"></i></a>
                            </div>
                            <div>
                                    <label>IntelligencePro</label>
                                    <a href="/pentaho/Login" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                                    <span class="spacer"><i class="fa fa-search fa-lg"></i></span>
                            </div>
                            <div>
                                    <label>SurveyPro</label>
                                    <a href="/AdaptikSurvey/AMEntryPoint?theme=adaptik-light&pageCode=HOME" target="_blank"><i class="fa fa-home fa-lg"></i></a>
                                    <a href="/AdaptikSurvey/AMEntryPoint?theme=adaptik-light&pageCode=SEARCH" target="_blank"><i class="fa fa-search fa-lg"></i></a>
                                    <a href="/PDSurvey" target="_blank"><i class="fa fa-gear fa-lg"></i></a>
                            </div>
                    </div>
            </body>
    </html>


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  1024;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';

      access_log	/var/log/nginx/access.log main;

      sendfile            on;
      tcp_nopush          on;
      tcp_nodelay         on;
      keepalive_timeout   65;
      types_hash_max_size 4096;

      client_max_body_size 100M;
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  nginx


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx
          readOnly: true
        - name: log
          mountPath: /var/log/nginx
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: log
        emptyDir: {}
